import { z } from 'zod';

/**
 * Finding Types supported by the system
 */
export type FindingType =
  | 'SINGLE_EVENT_FACT'
  | 'RECURRING_TOPIC_FOCUS'
  | 'COLLABORATION_PATTERN'
  | 'TEMPORAL_SEQUENCE'
  | 'ARCHITECTURAL_DECISION'
  | 'COGNITIVE_CLUSTER';

export const FindingTypeSchema = z.enum([
  'SINGLE_EVENT_FACT',
  'RECURRING_TOPIC_FOCUS',
  'COLLABORATION_PATTERN',
  'TEMPORAL_SEQUENCE',
  'ARCHITECTURAL_DECISION',
  'COGNITIVE_CLUSTER',
]);

/**
 * Structured Candidate Finding generated by upstream Cognitive Engine discovery
 */
export interface CandidateFinding {
  id: string;
  userId: string;
  findingType: FindingType;
  summary: string;
  statement: string;
  subjectEntityId?: string;
  objectEntityId?: string;
  involvedEntityIds: string[];
  involvedMemoryIds: string[];
  involvedRelationshipIds: string[];
  temporalScope: {
    startDate: Date;
    endDate: Date;
  };
  deterministicMetrics: {
    distinctFragmentCount: number;
    totalMentionCount?: number;
    densityScore?: number;
    frequencyPerWeek?: number;
    [key: string]: unknown;
  };
  discoveryAlgorithm: string;
  discoveryVersion: string;
  discoveryConfidence: number; // 0.0 to 1.0 (from upstream discovery metric)
  provenanceReferences: {
    fragmentId: string;
    contentHash: string;
    capturedAt: Date;
  }[];
  metadata?: Record<string, unknown>;
}

export const CandidateFindingSchema = z.object({
  id: z.string().min(1),
  userId: z.string().uuid(),
  findingType: FindingTypeSchema,
  summary: z.string().min(1),
  statement: z.string().min(1),
  subjectEntityId: z.string().uuid().optional(),
  objectEntityId: z.string().uuid().optional(),
  involvedEntityIds: z.array(z.string().uuid()).default([]),
  involvedMemoryIds: z.array(z.string().uuid()).default([]),
  involvedRelationshipIds: z.array(z.string().uuid()).default([]),
  temporalScope: z.object({
    startDate: z.coerce.date(),
    endDate: z.coerce.date(),
  }),
  deterministicMetrics: z.object({
    distinctFragmentCount: z.number().int().nonnegative(),
    totalMentionCount: z.number().int().nonnegative().optional(),
    densityScore: z.number().optional(),
    frequencyPerWeek: z.number().optional(),
  }).passthrough(),
  discoveryAlgorithm: z.string().min(1),
  discoveryVersion: z.string().min(1),
  discoveryConfidence: z.number().min(0.0).max(1.0),
  provenanceReferences: z.array(
    z.object({
      fragmentId: z.string().uuid(),
      contentHash: z.string().length(64),
      capturedAt: z.coerce.date(),
    })
  ).default([]),
  metadata: z.record(z.unknown()).optional(),
});

/**
 * Types of evidence objects supporting a finding
 */
export type EvidenceObjectType =
  | 'COGNITIVE_FRAGMENT'
  | 'MEMORY_NODE'
  | 'CANONICAL_ENTITY'
  | 'RELATIONSHIP_ASSERTION'
  | 'TEMPORAL_OBSERVATION';

export const EvidenceObjectTypeSchema = z.enum([
  'COGNITIVE_FRAGMENT',
  'MEMORY_NODE',
  'CANONICAL_ENTITY',
  'RELATIONSHIP_ASSERTION',
  'TEMPORAL_OBSERVATION',
]);

/**
 * Concrete atomic evidence object
 */
export interface EvidenceObject {
  id: string;
  userId: string;
  evidenceType: EvidenceObjectType;
  sourceId: string;
  sourceContentHash?: string;
  sourceTimestamp?: Date;
  validFrom?: Date;
  validTo?: Date;
  summary: string;
  verified: boolean;
  verificationDetails?: string;
  metadata?: Record<string, unknown>;
}

export const EvidenceObjectSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  evidenceType: EvidenceObjectTypeSchema,
  sourceId: z.string().uuid(),
  sourceContentHash: z.string().length(64).optional(),
  sourceTimestamp: z.coerce.date().optional(),
  validFrom: z.coerce.date().optional(),
  validTo: z.coerce.date().optional(),
  summary: z.string(),
  verified: z.boolean(),
  verificationDetails: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
});

/**
 * Rule Evaluation Result
 */
export interface RuleEvaluationResult {
  ruleId: string;
  ruleName: string;
  passed: boolean;
  resultingStatus?: ClaimStatus;
  scoreImpact: number;
  details: string;
  evidenceIdsEvaluated: string[];
}

/**
 * Complete machine-verifiable Evidence Chain
 */
export interface EvidenceChain {
  id: string;
  userId: string;
  findingId: string;
  evidenceObjects: EvidenceObject[];
  rootFragmentIds: string[];
  ruleEvaluations: RuleEvaluationResult[];
  isVerified: boolean;
  verificationTimestamp: Date;
  chainIntegrityHash: string; // Lexicographically sorted canonical SHA-256 hash
  createdAt: Date;
}

export const EvidenceChainSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  findingId: z.string().min(1),
  evidenceObjects: z.array(EvidenceObjectSchema),
  rootFragmentIds: z.array(z.string().uuid()),
  isVerified: z.boolean(),
  verificationTimestamp: z.coerce.date(),
  chainIntegrityHash: z.string().length(64),
  createdAt: z.coerce.date(),
});

/**
 * Claim Status enums
 */
export type ClaimStatus =
  | 'VALIDATED'
  | 'REJECTED'
  | 'INSUFFICIENT_EVIDENCE'
  | 'CONTRADICTED';

export const ClaimStatusSchema = z.enum([
  'VALIDATED',
  'REJECTED',
  'INSUFFICIENT_EVIDENCE',
  'CONTRADICTED',
]);

/**
 * Validated Claim produced by Reasoning Engine
 */
export interface ValidatedClaim {
  id: string;
  userId: string;
  sourceFindingId: string;
  evidenceChainId: string;
  claimType: FindingType;
  status: ClaimStatus;
  subjectEntityId?: string;
  objectEntityId?: string;
  statement: string;
  deterministicSupportScore: number;
  appliedRuleIds: string[];
  passedRuleIds: string[];
  failedRuleIds: string[];
  rejectionReason?: string;
  temporalScope: {
    startDate: Date;
    endDate: Date;
  };
  reasoningEngineVersion: string;
  createdAt: Date;
  updatedAt: Date;
}

export const ValidatedClaimSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  sourceFindingId: z.string().min(1),
  evidenceChainId: z.string().uuid(),
  claimType: FindingTypeSchema,
  status: ClaimStatusSchema,
  subjectEntityId: z.string().uuid().optional(),
  objectEntityId: z.string().uuid().optional(),
  statement: z.string().min(1),
  deterministicSupportScore: z.number().min(0.0).max(1.0),
  appliedRuleIds: z.array(z.string()),
  passedRuleIds: z.array(z.string()),
  failedRuleIds: z.array(z.string()),
  rejectionReason: z.string().optional(),
  temporalScope: z.object({
    startDate: z.coerce.date(),
    endDate: z.coerce.date(),
  }),
  reasoningEngineVersion: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

/**
 * Context passed to reasoning rules during evaluation
 */
export interface ReasoningRuleContext {
  userId: string;
  finding: CandidateFinding;
  evidence: EvidenceObject[];
  rootFragments: { id: string; contentHash: string; capturedAt: Date }[];
  entities: Map<string, any>;
  relationships: Map<string, any>;
  memories: Map<string, any>;
  evaluationTimestamp: Date; // Explicit evaluation reference timestamp (Zero wall-clock dependency)
}

/**
 * Interface for individual deterministic reasoning rules
 */
export interface IReasoningRule {
  readonly ruleId: string;
  readonly ruleName: string;
  evaluate(context: ReasoningRuleContext): Promise<RuleEvaluationResult>;
}

/**
 * Request & Response contracts for evaluation
 */
export interface EvaluateFindingRequest {
  userId: string;
  finding: CandidateFinding;
  evaluationTimestamp?: Date; // Optional; if omitted, callers provide explicitly or defaults to request time
}

export interface EvaluateFindingResponse {
  success: boolean;
  claim: ValidatedClaim;
  evidenceChain: EvidenceChain;
  executionTimeMs: number;
}
